services:
  web:
    build: ./app
    command: >
      sh -c "pip install debugpy &&
             python -m debugpy --listen 0.0.0.0:5678 --wait-for-client manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8000:8000
      - 5678:5678  # Debug port
    env_file:
      - ./.env.dev
    depends_on:
      - db
    environment:
      - PYTHONPATH=/usr/src/app
      - DJANGO_SETTINGS_MODULE=hello_django.settings
  
  db:
    image: postgres:16.10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django_123
      - POSTGRES_DB=hello_django_dev
    ports:
      - 5434:5432

volumes:
  postgres_data: